### ISSUE TITLE
Create post mutation creates duplicate post

### ISSUE THREAD

**Issue by state0fmind** [graphql-boilerplates/node-graphql-server#59] opened 2017-12-24 22:23 UTC
`mutation createPost {
  writePost(title: "Why GraphQL will change your life!", text: "Rest in pieces") {
    id
  }
}`

This creates duplicate post every time, effectively creating two posts. The writePost resolver is called only once though, which makes me think there's some issue with ctx.db.mutation.createPost. 

Also can anyone explain where does this db.mutation.createPost come from?

**Comment by state0fmind** [comment] 2017-12-26 13:38
https://github.com/graphcool/framework/issues/1454

**Comment by marktani** [comment] 2017-12-29 09:39
What do you mean it creates duplicate posts?

If you call this mutation once, one post should be created.
If you call this mutation twice, two posts should be created.

Do you observe a different behaviour?

**Comment by state0fmind** [comment] 2017-12-29 13:08
Yes, whenever I press play button in the graphql playground ide, it creates two posts/users in create user/writepost mutation.

**Comment by marktani** [comment] 2017-12-29 13:17
Yep, I can reproduce this. Here's what I tried:

* can reproduce in Playground
* can reproduce using cURL
* cannot reproduce when writing the mutation manually against the Graphcool DB

This makes me believe the problem is in [`graphcool-binding`](https://github.com/graphcool/graphcool-binding). I will look into the exact problem.

**Comment by marktani** [comment] 2017-12-29 14:10
Hey @state0fmind, which boilerplate example are you following exactly?

**Comment by state0fmind** [comment] 2017-12-30 10:14
@marktani the repo https://github.com/state0fmind/refract is a copy of node-advanced, just in es6

**Comment by allanleonardjr** [comment] 2018-01-02 00:27
Yikes @marktani, the duplication issue is occuring within my projects as well!
I've tested with the following templates:
- node-basic
- react-fullstack-basic

`$ graphcool -v`
`graphcool/1.0.0-beta2.1.1 (darwin-x64) node-v8.4.0`

`$ graphql -v`
`2.2.4`

**Comment by kbrandwijk** [comment] 2018-01-04 07:43
@state0fmind @allanleonardjr This is fixed in the latest version of `graphcool-binding`.

**Comment by marktani** [comment] 2018-01-04 09:51
Thanks! 🙌

**Closed by marktani** 2018-01-04 09:51 UTC

**Comment by schickling** [comment] 2018-01-04 10:30
This is now fixed in `graphcool-binding@1.2.2`: https://github.com/graphcool/graphcool-binding/pull/44

**Comment by allanleonardjr** [comment] 2018-01-04 16:36
Awesome, thanks!!!
